restructure makefiles, scripts to factor out O= logic. remove a few hardcoded paths elsewhere too.
R=r,gri
DELTA=123  (44 added, 15 deleted, 64 changed)
OCL=29914
CL=29945

diff --git a/src/cmd/gc/mkbuiltin b/src/cmd/gc/mkbuiltin
--- a/src/cmd/gc/mkbuiltin
+++ b/src/cmd/gc/mkbuiltin
@@ -4,11 +4,18 @@
 # license that can be found in the LICENSE file.
 
 set -e
+
+. $GOROOT/src/Make.$GOARCH
+if [ -z "$GC" ]; then
+	echo 'missing $GC - maybe no Make.$GOARCH?' 1>&2
+	exit 1
+fi
+
 gcc -o mkbuiltin1 mkbuiltin1.c
 rm -f _builtin.c
 for i in sys unsafe
 do
-	6g $i.go
+	$GC $i.go
 	./mkbuiltin1 $i >>_builtin.c
 done
 
diff --git a/src/cmd/gotest/gotest b/src/cmd/gotest/gotest
--- a/src/cmd/gotest/gotest
+++ b/src/cmd/gotest/gotest
@@ -8,18 +8,20 @@
 # tests.
 # If files are named on the command line, use them instead of test*.go.
 
-case "$GOARCH" in
-amd64)	O=6;;
-arm)	O=5;;
-386)	O=8;;
-*)	echo 'unknown $GOARCH' 1>&2
-esac
+_GC=$GC	# Make.$GOARCH will overwrite this
 
-GC=${GC:-${O}g}
-GL=${GL:-${O}l}
-export GC GL
+. $GOROOT/src/Make.$GOARCH
+if [ -z "$O" ]; then
+	echo 'missing $O - maybe no Make.$GOARCH?' 1>&2
+	exit 1
+fi
+
+# Allow overrides
+GC=${_GC:-$GC}
+GL=${GL:-$LD}
 GC="$GC -I _obj"
 GL="$GL -L _obj"
+export GC GL
 
 gofiles=""
 loop=true
