build: $GOBIN defaults to $GOROOT/bin
R=r
CC=golang-dev
https://golang.org/cl/1982049

diff --git a/src/cmd/gc/mkbuiltin b/src/cmd/gc/mkbuiltin
--- a/src/cmd/gc/mkbuiltin
+++ b/src/cmd/gc/mkbuiltin
@@ -10,11 +10,9 @@
 
 set -e
 
-GOBIN="${GOBIN:-$HOME/bin}"
-
-eval $("$GOBIN"/gomake -f ../../Make.inc go-env)
+eval $(gomake -f ../../Make.inc go-env)
 if [ -z "$GC" ]; then
-	echo 'missing $GC - maybe no Make.$GOARCH?' 1>&2
+	echo 'missing $GC - gomake failed?' 1>&2
 	exit 1
 fi
 
